### ISSUE TITLE
Massive performance regression since commit fbd332d

### ISSUE THREAD

**Issue by Edensan** [facebook/yoga#734]
# Report

- [x] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

The recent move to "OOP" patterns and code structures has heavily impacted performance as can be seen when running benchmarks:

TAG [1.8.0]
Stack with flex: median: 0.027000 ms, stddev: 0.005840 ms
Align stretch in undefined axis: median: 0.027000 ms, stddev: 0.005836 ms
Nested flex: median: 0.436000 ms, stddev: 0.067741 ms
Huge nested layout: median: 36.938000 ms, stddev: 2.847124 ms

COMMIT [fbd332d]
Stack with flex: median: 0.042000 ms, stddev: 0.007671 ms
Align stretch in undefined axis: median: 0.036000 ms, stddev: 0.009329 ms
Nested flex: median: 0.748000 ms, stddev: 0.108319 ms
Huge nested layout: median: 50.196000 ms, stddev: 3.076368 ms

TAG [1.7.0]
Stack with flex: median: 0.010000 ms, stddev: 0.006567 ms
Align stretch in undefined axis: median: 0.012000 ms, stddev: 0.002526 ms
Nested flex: median: 0.152000 ms, stddev: 0.038512 ms
Huge nested layout: median: 12.710000 ms, stddev: 1.497397 ms

As far as I understand mostly due to unnecessary copies all over the place.
I'm not sure if this is a known issue, but I suggest taking a look at it before it becomes too hard to optimize/refactor.

**Comment by koxen** [comment]
any update?

**Comment by emilsjolander** [comment]
Thanks for the report! We will look into this!

**Comment by koxen** [comment]
@emilsjolander am I right that this was corrected here https://github.com/facebook/yoga/commit/cda328fa7e5392213121edaaebb97b95f60d10f6?

**Comment by emilsjolander** [comment]
@koxen I think so but would be good to confirm

**Comment by koxen** [comment]
@emilsjolander that would be great, would you mind bumping react-native to a beta version after you're done? :)

**Comment by Edensan** [comment]
@emilsjolander @koxen 
I have been tracking changes and have already profiled this and no, it didn't solve the issue.

Stack with flex: median: 0.033000 ms, stddev: 0.008888 ms
Align stretch in undefined axis: median: 0.032000 ms, stddev: 0.008994 ms
Nested flex: median: 0.561000 ms, stddev: 0.120899 ms
Huge nested layout: median: 39.258000 ms, stddev: 2.278808 ms

**Comment by Edensan** [comment]
There are multiple places in the code where the YGLayout and/or YGStyle are being copied instead of referenced... 
eg.
```cpp
#define YG_NODE_STYLE_PROPERTY_SETTER_IMPL(                               \
    type, name, paramName, instanceName)                                  \
  void YGNodeStyleSet##name(const YGNodeRef node, const type paramName) { \
    if (node->getStyle().instanceName != paramName) {                     \
      YGStyle style = node->getStyle();                                   \
      style.instanceName = paramName;                                     \
      node->setStyle(style);                                              \
      node->markDirtyAndPropogate();                                      \
    }                                                                     \
  }
```
1. Style is copied
2. Value changed
3. Source style overwritten by copy

............ Why??
Should just be the following:
```cpp
#define YG_NODE_STYLE_PROPERTY_SETTER_IMPL(                               \
    type, name, paramName, instanceName)                                  \
  void YGNodeStyleSet##name(const YGNodeRef node, const type paramName) { \
    YGStyle& style = node->getStyle();                                    \
    if (style.instanceName != paramName) {                                \
      style.instanceName = paramName;                                     \
      node->markDirtyAndPropogate();                                      \
    }                                                                     \
  }
```

There are many more such places in the code...

**Comment by Edensan** [comment]
Note that I've tried and cleaned up most of the YGStyle and YGLayout copies and still did not change that much, just a few percents which makes me think that there may be something ugly going on somewhere.

**Comment by woehrl01** [comment]
@Edensan yes, those macros should be adapted, but they aren't heavily used in the benchmark tool. 

After having a look throughout the code, my assumption about the performance penality is that the implementation of the `YGNode` getters aren't decleared directly in the `YGNode` header. This could lead to the behaviour that this calls aren't inlined correctly (as it only sees the `YGNode.h` definition and not the concrete implementation inside `Yoga.cpp`). 
I haven't verified that this is the root cause here, but I experienced similar things in other projects.

**Comment by Edensan** [comment]
@woehrl01 Got it.

Since you mentioned it, I suppose refreshing the benchmarks might also be a good idea.

**Comment by koxen** [comment]
I am seeing noticable performance improvement in my RN app(FlatList, items using lots of flexboxes) after upgrading to version with https://github.com/facebook/yoga/commit/cda328fa7e5392213121edaaebb97b95f60d10f6...so it seems related. I would appreciate further pass-by-reference fixes like @Edensan pointed out :)

**Comment by Edensan** [comment]
Is there someone working on this issue at the moment? Would be nice to keep us updated.

**Comment by gengjiawen** [comment]
Looks like still not fixed.

From  the benchmark, Yoga 1.6.0 is two times faster than 1.14.0.

https://gist.github.com/gengjiawen/141051afa3aa2d6745e86be69c60c2fb
